version: 2
updates:
  - package-ecosystem: pip
    directoryies:
      - "/backend"
      - "/bot"
      - "/events"
      - "/integration"
      - "/tools"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
  - package-ecosystem: docker
    directories:
      - "/backend"
      - "/bot/docker"
      - "/events/docker"
      - "/integration/docker"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
